clear;
clc;
T = 1;
fs = 10;
L = 6;
t1 = (-6*T:T/fs:6*T);
beta = 0;
RC_1 = raised_cosine(t1, beta, T);
RC_1(isinf(RC_1)) = (pi/(T*4))*(sin((pi)/(2*beta)))./((pi)/2*beta);
RC_1(isnan(RC_1)) = 1;
modulated_symbol = randsrc(1,10^6,[-3 -1 1 3; 0.1 0.4 0.4 0.1]);
temp = upsample(modulated_symbol, L);
temp = temp(1:end-(L-1));
transmitted_signal = conv(temp, RC_1);
noise = randn(1,length(transmitted_signal));
SNR_dB = 0:10;
snr = 10.^(SNR_dB./10);
eta = var(transmitted_signal)./snr;
noise = diag(sqrt(eta./2))*repmat(noise,11,1);
received_signal = repmat(transmitted_signal, 11, 1) + noise;
